/**
 * Compliance Balance (CB) Entity
 * 
 * Represents the compliance balance for a ship in a specific year.
 * 
 * Business Rules:
 * - CB is calculated based on energy in scope and GHG intensity difference
 * - Positive CB = surplus (can be banked or pooled)
 * - Negative CB = deficit (needs banking/pooling to comply)
 * - CB can be adjusted by banking (using previous surplus)
 * - Final CB after adjustments determines compliance status
 */

/**
 * FuelEU Maritime GHG Intensity Targets (gCO₂e/MJ)
 * Source: FuelEU Maritime Regulation
 */
export const FUELEU_TARGETS: Record<number, number> = {
  2025: 89.3368,  // 2% reduction from 91.16 baseline
  2026: 87.7528,  // 4% reduction
  2027: 86.1688,  // 6% reduction
  2028: 84.5848,  // 8% reduction
  2029: 83.0008,  // 10% reduction
  2030: 81.4168,  // 13% reduction
};

/**
 * Compliance Balance Properties
 */
export interface IComplianceBalanceProps {
  id?: string;                    // UUID (optional, generated by database)
  shipId: string;                 // Ship identifier
  year: number;                   // Year (2025-2030)
  energyInScope: number;          // Energy consumed in MJ
  ghgTarget: number;              // FuelEU target GHG intensity (gCO₂e/MJ)
  ghgActual: number;              // Actual GHG intensity (gCO₂e/MJ)
  multiplier: number;             // Multiplier (M) - usually 1.0
  complianceBalance: number;      // Calculated CB in gCO₂e
  bankedAmount?: number;          // Amount banked from this year
  borrowedAmount?: number;        // Amount borrowed for this year
  adjustedCB?: number;            // CB after banking adjustments
}

/**
 * Compliance Balance Entity
 */
export class ComplianceBalance {
  
  // Private properties (encapsulation)
  private readonly id?: string;
  private readonly shipId: string;
  private readonly year: number;
  private readonly energyInScope: number;
  private readonly ghgTarget: number;
  private readonly ghgActual: number;
  private readonly multiplier: number;
  private complianceBalance: number;
  private bankedAmount: number;
  private borrowedAmount: number;
  private adjustedCB: number;

  /**
   * Constructor
   */
  constructor(props: IComplianceBalanceProps) {
    // Validate
    this.validate(props);
    
    // Set properties
    this.id = props.id;
    this.shipId = props.shipId;
    this.year = props.year;
    this.energyInScope = props.energyInScope;
    this.ghgTarget = props.ghgTarget;
    this.ghgActual = props.ghgActual;
    this.multiplier = props.multiplier;
    this.complianceBalance = props.complianceBalance;
    this.bankedAmount = props.bankedAmount || 0;
    this.borrowedAmount = props.borrowedAmount || 0;
    this.adjustedCB = props.adjustedCB || props.complianceBalance;
  }

  /**
   * Validation
   */
  private validate(props: IComplianceBalanceProps): void {
    if (!props.shipId || props.shipId.trim() === '') {
      throw new Error('Ship ID is required');
    }

    if (props.year < 2025 || props.year > 2030) {
      throw new Error('Year must be between 2025 and 2030');
    }

    if (props.energyInScope <= 0) {
      throw new Error('Energy in scope must be positive');
    }

    if (props.ghgTarget <= 0 || props.ghgActual <= 0) {
      throw new Error('GHG intensities must be positive');
    }

    if (props.multiplier <= 0) {
      throw new Error('Multiplier must be positive');
    }
  }

  /**
   * STATIC FACTORY METHOD: Create from Route
   * 
   * This is a convenience method to calculate CB from a route
   * 
   * @param shipId - Ship identifier
   * @param year - Year for compliance
   * @param fuelConsumption - Fuel consumed in tonnes
   * @param ghgActual - Actual GHG intensity (gCO₂e/MJ)
   * @param multiplier - Multiplier (default 1.0)
   * @returns New ComplianceBalance instance
   */
  static createFromRoute(
    shipId: string,
    year: number,
    fuelConsumption: number,
    ghgActual: number,
    multiplier: number = 1.0
  ): ComplianceBalance {
    
    // Get FuelEU target for the year
    const ghgTarget = FUELEU_TARGETS[year];
    
    if (!ghgTarget) {
      throw new Error(`No FuelEU target defined for year ${year}`);
    }

    // Calculate energy in scope (MJ)
    // 1 tonne of fuel = 41,000 MJ (from FuelEU regulation)
    const energyInScope = fuelConsumption * 41000;

    // Calculate Compliance Balance
    // CB = Energy × (Target - Actual) × M
    const complianceBalance = energyInScope * (ghgTarget - ghgActual) * multiplier;

    // Create instance
    return new ComplianceBalance({
      shipId,
      year,
      energyInScope,
      ghgTarget,
      ghgActual,
      multiplier,
      complianceBalance,
    });
  }

  /**
   * BUSINESS LOGIC: Is Compliant?
   * 
   * A ship is compliant if adjusted CB >= 0
   */
  isCompliant(): boolean {
    return this.adjustedCB >= 0;
  }

  /**
   * BUSINESS LOGIC: Has Surplus?
   */
  hasSurplus(): boolean {
    return this.complianceBalance > 0;
  }

  /**
   * BUSINESS LOGIC: Has Deficit?
   */
  hasDeficit(): boolean {
    return this.complianceBalance < 0;
  }

  /**
   * BUSINESS LOGIC: Get Surplus Amount
   */
  getSurplusAmount(): number {
    return this.hasSurplus() ? this.complianceBalance : 0;
  }

  /**
   * BUSINESS LOGIC: Get Deficit Amount
   */
  getDeficitAmount(): number {
    return this.hasDeficit() ? Math.abs(this.complianceBalance) : 0;
  }

  /**
   * BUSINESS LOGIC: Apply Banking
   * 
   * Use banked credits from previous years to offset deficit
   * 
   * @param amount - Amount to apply (in gCO₂e)
   */
  applyBanking(amount: number): void {
    if (amount < 0) {
      throw new Error('Banking amount must be positive');
    }

    this.borrowedAmount += amount;
    this.adjustedCB = this.complianceBalance + this.borrowedAmount - this.bankedAmount;
  }

  /**
   * BUSINESS LOGIC: Bank Surplus
   * 
   * Save surplus for future years
   * 
   * @param amount - Amount to bank (in gCO₂e)
   */
  bankSurplus(amount: number): void {
    if (amount < 0) {
      throw new Error('Bank amount must be positive');
    }

    if (amount > this.getSurplusAmount()) {
      throw new Error('Cannot bank more than surplus amount');
    }

    this.bankedAmount += amount;
    this.adjustedCB = this.complianceBalance + this.borrowedAmount - this.bankedAmount;
  }

  /**
   * BUSINESS LOGIC: Calculate Penalty
   * 
   * If still non-compliant after adjustments, calculate penalty
   * Penalty = 2400 EUR per tonne of CO₂ deficit
   * 
   * @returns Penalty in EUR
   */
  calculatePenalty(): number {
    if (this.isCompliant()) {
      return 0;
    }

    // Convert gCO₂e to tonnes
    const deficitInTonnes = Math.abs(this.adjustedCB) / 1000000;
    
    // FuelEU penalty: 2400 EUR per tonne
    return deficitInTonnes * 2400;
  }

  // ========================================
  // GETTERS
  // ========================================

  getId(): string | undefined {
    return this.id;
  }

  getShipId(): string {
    return this.shipId;
  }

  getYear(): number {
    return this.year;
  }

  getEnergyInScope(): number {
    return this.energyInScope;
  }

  getGHGTarget(): number {
    return this.ghgTarget;
  }

  getGHGActual(): number {
    return this.ghgActual;
  }

  getMultiplier(): number {
    return this.multiplier;
  }

  getComplianceBalance(): number {
    return this.complianceBalance;
  }

  getBankedAmount(): number {
    return this.bankedAmount;
  }

  getBorrowedAmount(): number {
    return this.borrowedAmount;
  }

  getAdjustedCB(): number {
    return this.adjustedCB;
  }

  /**
   * Convert to plain object
   */
  toObject(): IComplianceBalanceProps {
    return {
      id: this.id,
      shipId: this.shipId,
      year: this.year,
      energyInScope: this.energyInScope,
      ghgTarget: this.ghgTarget,
      ghgActual: this.ghgActual,
      multiplier: this.multiplier,
      complianceBalance: this.complianceBalance,
      bankedAmount: this.bankedAmount,
      borrowedAmount: this.borrowedAmount,
      adjustedCB: this.adjustedCB,
    };
  }
}