/**
 * Route Domain Entity
 * 
 * This is a PURE domain entity - no framework dependencies!
 * Represents a maritime shipping route with fuel and emissions data.
 * 
 * Business Rules:
 * - Route ID must be unique
 * - Year must be between 2024-2030
 * - All numeric values must be positive
 * - Only ONE route can be baseline at a time
 * - Can calculate total emissions from fuel consumption
 */

/**
 * Enum: Vessel Types
 * 
 * The types of ships in FuelEU regulation
 */
export enum VesselType {
  CONTAINER = 'Container',
  BULK_CARRIER = 'BulkCarrier',
  TANKER = 'Tanker',
  RORO = 'RoRo',
}

/**
 * Enum: Fuel Types
 * 
 * The types of marine fuels
 */
export enum FuelType {
  HFO = 'HFO',  // Heavy Fuel Oil
  LNG = 'LNG',  // Liquefied Natural Gas
  MGO = 'MGO',  // Marine Gas Oil
}

/**
 * Interface: Route Properties
 * 
 * Defines what data is needed to create a Route
 */
export interface IRouteProps {
  id?: string;                    // UUID (optional, generated by database)
  routeId: string;                // Route identifier (R001, R002, etc.)
  vesselType: VesselType;         // Type of vessel
  fuelType: FuelType;             // Type of fuel used
  year: number;                   // Year (2024, 2025, etc.)
  ghgIntensity: number;           // GHG intensity in gCO₂e/MJ
  fuelConsumption: number;        // Fuel consumed in tonnes
  distance: number;               // Distance traveled in kilometers
  isBaseline: boolean;            // Is this the baseline route?
}

/**
 * Route Entity
 * 
 * This is the heart of our domain model.
 * Contains both DATA and BEHAVIOR.
 */
export class Route {
  
  // Private properties (encapsulation)
  // Only accessible through getter methods
  private readonly id?: string;
  private readonly routeId: string;
  private readonly vesselType: VesselType;
  private readonly fuelType: FuelType;
  private readonly year: number;
  private readonly ghgIntensity: number;
  private readonly fuelConsumption: number;
  private readonly distance: number;
  private isBaseline: boolean;

  /**
   * Constructor
   * 
   * Creates a new Route and validates all data
   * Throws error if data is invalid
   */
  constructor(props: IRouteProps) {
    // Validate before creating
    this.validate(props);
    
    // Set all properties
    this.id = props.id;
    this.routeId = props.routeId;
    this.vesselType = props.vesselType;
    this.fuelType = props.fuelType;
    this.year = props.year;
    this.ghgIntensity = props.ghgIntensity;
    this.fuelConsumption = props.fuelConsumption;
    this.distance = props.distance;
    this.isBaseline = props.isBaseline;
  }

  /**
   * Validation Logic
   * 
   * Ensures all business rules are followed
   * This is DOMAIN LOGIC - independent of database or HTTP
   */
  private validate(props: IRouteProps): void {
    // Rule 1: Route ID is required
    if (!props.routeId || props.routeId.trim() === '') {
      throw new Error('Route ID is required');
    }

    // Rule 2: Year must be in valid range
    if (props.year < 2024 || props.year > 2030) {
      throw new Error('Year must be between 2024 and 2030');
    }

    // Rule 3: GHG intensity must be positive
    if (props.ghgIntensity <= 0) {
      throw new Error('GHG intensity must be positive');
    }

    // Rule 4: Fuel consumption must be positive
    if (props.fuelConsumption <= 0) {
      throw new Error('Fuel consumption must be positive');
    }

    // Rule 5: Distance must be positive
    if (props.distance <= 0) {
      throw new Error('Distance must be positive');
    }
  }

  /**
   * Business Logic: Calculate Total Emissions
   * 
   * Formula from FuelEU regulation:
   * 1. Calculate energy in scope: fuelConsumption (tonnes) × 41,000 MJ/tonne
   * 2. Calculate emissions: ghgIntensity (gCO₂e/MJ) × energy (MJ)
   * 3. Convert to tonnes: emissions (g) / 1,000,000
   * 
   * @returns Total emissions in tonnes of CO₂e
   */
  calculateTotalEmissions(): number {
    // Energy in scope (MJ)
    const energyInScope = this.fuelConsumption * 41000;
    
    // Emissions in grams
    const emissionsInGrams = this.ghgIntensity * energyInScope;
    
    // Convert to tonnes
    return emissionsInGrams / 1000000;
  }

  /**
   * Business Logic: Compare with Target
   * 
   * Calculates how this route compares to FuelEU target
   * 
   * @param targetIntensity - The FuelEU target (e.g., 89.3368 for 2025)
   * @returns Percentage difference (negative = better than target)
   */
  compareWithTarget(targetIntensity: number): number {
    // Formula: ((actual - target) / target) × 100
    return ((this.ghgIntensity - targetIntensity) / targetIntensity) * 100;
  }

  /**
   * Business Logic: Is Compliant?
   * 
   * Checks if route meets FuelEU target
   * 
   * @param targetIntensity - The FuelEU target
   * @returns true if compliant, false if not
   */
  isCompliant(targetIntensity: number): boolean {
    // Compliant if actual intensity is BELOW target
    return this.ghgIntensity <= targetIntensity;
  }

  // ========================================
  // GETTERS (Read-only access to properties)
  // ========================================

  getId(): string | undefined {
    return this.id;
  }

  getRouteId(): string {
    return this.routeId;
  }

  getVesselType(): VesselType {
    return this.vesselType;
  }

  getFuelType(): FuelType {
    return this.fuelType;
  }

  getYear(): number {
    return this.year;
  }

  getGHGIntensity(): number {
    return this.ghgIntensity;
  }

  getFuelConsumption(): number {
    return this.fuelConsumption;
  }

  getDistance(): number {
    return this.distance;
  }

  getIsBaseline(): boolean {
    return this.isBaseline;
  }

  // ========================================
  // BUSINESS OPERATIONS
  // ========================================

  /**
   * Set this route as baseline
   * 
   * Business rule: Only call this after removing baseline from others
   */
  setAsBaseline(): void {
    this.isBaseline = true;
  }

  /**
   * Remove baseline status
   */
  removeAsBaseline(): void {
    this.isBaseline = false;
  }

  /**
   * Convert to plain object
   * 
   * Used by repository to save to database
   * 
   * @returns Plain object with all properties
   */
  toObject(): IRouteProps {
    return {
      id: this.id,
      routeId: this.routeId,
      vesselType: this.vesselType,
      fuelType: this.fuelType,
      year: this.year,
      ghgIntensity: this.ghgIntensity,
      fuelConsumption: this.fuelConsumption,
      distance: this.distance,
      isBaseline: this.isBaseline,
    };
  }
}